apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1
  namespace: argocd
spec:
  project: team1

  source:
    repoURL: https://github.com/CSU-ITMO-2025-2/team1-gitops
    targetRevision: main
    path: production
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: team1-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
