{{- if or .Values.rbac.enabled (and .Values.global.rbac .Values.global.rbac.enabled) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-frontend-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Release.Name }}-frontend-secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-frontend-secret-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-frontend-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-frontend-secret-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}

