{{- if .Values.autoscaling.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-question-worker-scaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-question-worker
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: rabbitmq
    metadata:
      protocol: http
      host: {{ .Release.Name }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
      port: "15672"
      queueName: {{ .Values.autoscaling.queueName }}
      queueLength: {{ .Values.autoscaling.queueLength | quote }}
      vhostName: "/"
{{- end }}
